url: http://www.nangrang.kr
baseurl: 

title: "[낭:랑]"
title-en: NangRang
slogan: "[낭:랑] 하게 [낭:랑] 하라!"
email: nangrang1@naver.com
description: 스토리가 있는 광고/마케팅 전문기업 낭랑,<br />오늘도 광고주님과 함께 스토리를 만들어 가겠습니다. 
ceo: 김민정
registration-number: 010-3199-7666

people:
- name: 김민정
  gravatar: 1
  quote: 광고마케팅 팀
  position: CEO
  history:
    - 매출과 직결되는 마케팅, 
    - 온라인 DB구축의 최적화 마케팅실현
  social:

- name: 윤나영
  gravatar: 2
  quote: 창업/마케팅교육 팀
  position: 과장
  history:
    - 아는만큼 보이는 마케팅,
    - 성공 창업/마케팅 전략

  social:

- name: 송유신 
  gravatar: 3
  quote: 온라인 쇼핑몰구축 팀
  position: 팀장
  email: moon@eazler.com
  history:
    - 70억 고객과 이어주는
    - 성공 쇼핑몰 창업/운영
  social:

- name: 강민승 
  gravatar: 4
  quote: 프랜차이즈 인큐베이팅 팀
  position: 팀장
  history:
    - 낭랑과 함께하면
    - 프랜차이즈가 즐거워집니다.

  social:

contact:
  - file: kakao
    url: https://story.kakao.com/ch/nangrang 
  - file: instagram
    url: https://www.instagram.com/nangrang1/ 
  - file: blog
    url: http://blog.naver.com/nangrang1 
  - file: facebook
    url: "https://www.facebook.com/#!/nangrang1/"  

address: 대구광역시 북구 동북로 117 소프트웨어벤처타워 15층 대구스마트워크센터 1507호

# Build settings
markdown: kramdown
permalink: pretty